/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-04-20 07:26:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hyehwamobile;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"../include/jquery-3.6.3.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css\" />\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function create() {\r\n");
      out.write("	 window.location.href=\"joinhyehwa.jsp\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div data-role=\"page\" id=\"page1\">\r\n");
      out.write("<div data-role=\"header\">\r\n");
      out.write("<h1> hyehwa plate 혜화동 맛집 뽀시기</h1>\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<div data-role=\"content\">\r\n");
      out.write("\r\n");
      out.write("<!-- <h2>혜화동 숨은 맛집을 찾아라</h2><br> -->\r\n");
      out.write("<h2> 먹고싶은 음식 종류를 선택하세요.</h2>\r\n");
      out.write(" <div data-role=\"panel\" id=\"panel1\" data-display=\"overlay\" data-theme=\"b\">\r\n");
      out.write("  ");
 String context=request.getContextPath(); 
      out.write("\r\n");
      out.write("	<form method=\"post\" action=\"");
      out.print( context);
      out.write("/ch02_servlet/login.do\">\r\n");
      out.write("		<h1>로그인</h1>\r\n");
      out.write("		<label for=\"name\">아이디 : </label>\r\n");
      out.write("	  <input type=\"text\" name=\"userid\" id=\"userid\" value=\"\" data-mini=\"true\" \r\n");
      out.write("	  data-clear-btn=\"true\">\r\n");
      out.write("	  <label for=\"password\">비밀번호 : </label>\r\n");
      out.write("		<input type=\"password\" id=\"passwd\" name=\"passwd\" value=\"\" data-mini=\"true\" \r\n");
      out.write("	  data-clear-btn=\"true\">\r\n");
      out.write("		<input type=\"submit\" value=\"로그인\">\r\n");
      out.write("		<input type=\"submit\" value=\"회원가입\" onclick= \"create()\" >\r\n");
      out.write("  </form>\r\n");
      out.write(" </div>\r\n");
      out.write("<ul  data-role=\"listview\" data-inset=\"true\">\r\n");
      out.write("  <li><a href=\"korea.jsp\" data-transition=\"slide\" >\r\n");
      out.write("      한정식</a></li>\r\n");
      out.write("    <li><a href=\"world.jsp\" data-transition=\"slide\" >\r\n");
      out.write("   양식</a></li>\r\n");
      out.write("    <li><a href=\"cafe.jsp\" data-transition=\"slide\" >\r\n");
      out.write("   카페.디저트</a></li>\r\n");
      out.write("    <li><a href=\"chicken.jsp\" data-transition=\"slide\" >\r\n");
      out.write("     치킨</a></li>\r\n");
      out.write("    <li><a href=\"alchol.jsp\" data-transition=\"slide\" >\r\n");
      out.write("     술집</a></li>\r\n");
      out.write("    <li><a href=\"eastern.jsp\" data-transition=\"slide\" >\r\n");
      out.write("     아시아음식</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("  <a href=\"#panel1\" data-role=\"button\" data-inline=\"true\">로그인 패널</a><br>\r\n");
      out.write("	<!-- 로그인 실패, 로그아웃 메시지를 출력 -->\r\n");
      out.write("	");

	String message=request.getParameter("message");
	if(message != null){
	
      out.write("\r\n");
      out.write("	<ul data-role=\"listview\" data-inset=\"true\">\r\n");
      out.write("	 <li data-theme=\"b\">메시지 : </li>\r\n");
      out.write("	 <li>");
      out.print( message );
      out.write("</li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div data-role=\"footer\">  \r\n");
      out.write(" <h4>Copyright &copy; 2023 hongminhwa</h4>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
