/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-04-20 08:27:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hyehwamobile;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class kimchi_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"../include/jquery-3.6.3.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css\" />\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div data-role=\"page\" id=\"page1\"> \r\n");
      out.write("<div data-role=\"header\">\r\n");
      out.write("<a href=\"Index.jsp\" data-icon=\"home\">홈</a> \r\n");
      out.write("<h1>탕(전골,찌게,국물류)</h1>\r\n");
      out.write("</div>\r\n");
      out.write("<div data-role=\"content\"> \r\n");
      out.write("<div class=\"ui-grid-a\"> \r\n");
      out.write("<div class=\"ui-block-a\"> \r\n");
      out.write("<h1> 이화김치찌게</h1>\r\n");
      out.write("<p>주소 서울 종로구 율곡로 216</p>\r\n");
      out.write("<p>(4호선)혜화역1번출구 500m</p>\r\n");
      out.write("<p>주차공간있긴하나 협소함</p>\r\n");
      out.write("<p>전화번호 0507-1447-9255</p>\r\n");
      out.write("<p>영업시간 매일 10:00~ 22:00</p>\r\n");
      out.write("<p>브레이크타임 15:00~17:00</p>\r\n");
      out.write("<h4>메뉴</h4>\r\n");
      out.write("<p>김치찌개 8000원 </p>\r\n");
      out.write("<p>계란말이 小 4000원 大 7000원</p>\r\n");
      out.write("<p>계란찜 3000원</p>\r\n");
      out.write("<p>생삼겹살(180g) 15000원</p>\r\n");
      out.write("<p>생목살(180g) 15000원</p>\r\n");
      out.write("<p>우삼겹살 13000원</p>\r\n");
      out.write("<p>부대/참치/꽁치 김치찌개 8000원 </p>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"ui-block-b\"> \r\n");
      out.write("   <img src=\"../korea/kimchi.jpg\"> \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<hr> \r\n");
      out.write("<div class=\"ui-grid-a\"> \r\n");
      out.write("<div class=\"ui-block-a\"> \r\n");
      out.write("<h2>옛날 어머니의 구수한 손맛을 느낄 수 있는 김치찌개와 생삼겹살 전문점입니다</h2>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"ui-block-b\">\r\n");
      out.write("<a href=\"https://place.map.kakao.com/1586032924\"\r\n");
      out.write(" data-role=\"button\" data-icon=\"location\">카카오맵에서 찾기</a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<hr> \r\n");
      out.write("<div>\r\n");
      out.write("<form>\r\n");
      out.write("<label for=\"select-choice\">\r\n");
      out.write("<h2> 사용자 평가</h2>\r\n");
      out.write("</label>\r\n");
      out.write("<select name=\"select-choice\" id=\"select-choice\" data-native-menu=\"false\" data-theme=\"b\"> \r\n");
      out.write("<option value=\"one\">Bad</option>\r\n");
      out.write("<option value=\"two\">Good</option>\r\n");
      out.write("<option value=\"three\">Great</option>\r\n");
      out.write("<option value=\"four\">Perfect</option>  \r\n");
      out.write("</select>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div data-role=\"footer\">  \r\n");
      out.write(" <h4>Copyright &copy; 2023 hongminhwa</h4>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
