/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-05-02 05:51:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hyehwaPC;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Index2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1678344190252L));
    _jspx_dependants.put("jar:file:/C:/work_javaKH/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jsp02/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/hyehwaPC/../include/header.jsp", Long.valueOf(1679567087703L));
    _jspx_dependants.put("jar:file:/C:/work_javaKH/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jsp02/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/work_javaKH/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jsp02/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"../include/jquery-3.6.3.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("1) jstl (jsp standard Tag Library, jsp 표준 태그 라이브러리 \r\n");
      out.write("2) jstl 사용 이유: model1은 jsp페이지 중심, model2는 java코드 중심, jsp웹페이지에서 \r\n");
      out.write("java코드를 안쓸 수는 없지만 이를 최소화 하기 위해서 jstl과 EL기법을 씀, \r\n");
      out.write("복잡한 자바코드를 대체하기 위한 태그 \r\n");
      out.write("3) taglib uri=\"태그라이브러리의 식별자=\" prefix=\"태그 접두어\" \r\n");
      out.write("4) Core tag(핵심태그, 제일 자주 사용되는 태그들) \r\n");
      out.write("  -->\r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/jquery-3.6.3.min.js\"></script>\r\n");
      out.write("   <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/js/bootstrap.js\"></script>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/css/bootstrap.css\">\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../hyehwaStyle/index2_style.css\"> \r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function create() {\r\n");
      out.write("	window.location.href='../hyehwa/join.jsp';\r\n");
      out.write("} \r\n");
      out.write(" \r\n");
      out.write("$(function() {\r\n");
      out.write("	 $(\"#btnLogout\").click(function() {\r\n");
      out.write("		 location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hyehwa_servlet/logout.do\"; \r\n");
      out.write("	});  \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function() {\r\n");
      out.write("	$(\"#btnList\").click(function() {\r\n");
      out.write("		 location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hyehwa_servlet/list.do\";\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"homepage\" onunload=\"\">\r\n");
      out.write("<main class=\"pg-main\"> \r\n");
      out.write("  <div class=\"main_screen\"> \r\n");
      out.write("  <img src=\"../picture/station1.jpg\" width=\"100%\" height=\"600px\"> \r\n");
      out.write("  <h1 class=\"main_screen_text2\">hyehwaplate</h1>\r\n");
      out.write("  <h1 class=\"main_screen_text\">혜화동 맛집을 정복하자! hyehwaplate</h1> \r\n");
      out.write("  </div>\r\n");
      out.write("    <header class=\"main-header\">     \r\n");
      out.write("   \r\n");
      out.write("   <fieldset class=\"main-search\"> \r\n");
      out.write(" <!--    <legend>전체 검색 </legend> -->   \r\n");
      out.write("    <label class=\"search-word\" for=\"main-search\"> \r\n");
      out.write("   <span class=\"icon\"> 검색</span> \r\n");
      out.write("   <input id=\"main-search\" class=\"HomeSearchInput\" name=\"main-search\" type=\"text\" maxlength=\"100\" placeholder=\"식당이나 먹고싶은 음식\" onclick=\"#\">\r\n");
      out.write("  <span class=\"clear_btn\">Clear</span>    \r\n");
      out.write("    </label>\r\n");
      out.write("   <input class=\"btn-search\" type=\"submit\" value=\"검색\" onclick=\"#\"> \r\n");
      out.write("   <!-- <button type=\"button\" value=\"회원가입\" id=\"btnCreate\" onclick=\"create()\">회원가입</button> -->\r\n");
      out.write("   </fieldset> \r\n");
      out.write("      ");
      out.print( request.getAttribute("result"));
      out.write("  \r\n");
      out.write("    <div style=\"text-align: right;\">\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write(" </div>\r\n");
      out.write("    </header>\r\n");
      out.write("</main>\r\n");
      out.write("<hr> \r\n");
      out.write("\r\n");
      out.write("<div class=\"title1\"> \r\n");
      out.write(" <h2>한국인은 밥心이지! 한정식</h2>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"rice\">\r\n");
      out.write("<a href=\"rice.jsp\">\r\n");
      out.write("<img class=\"rice2\" alt=\"한정식\" \r\n");
      out.write("src=\"../food/rice.jpg\" style=\"width:700px; height:250px\"/></a><br>\r\n");
      out.write("<strong class=\"rice2_text\">집밥이 그리울땐~ 백반맛집!</strong>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"soup\">  \r\n");
      out.write(" <a href=\"soup.jsp\">\r\n");
      out.write("<img class=\"soup2\" alt=\"한정식\"\r\n");
      out.write(" src=\"../food/soup.jpg\" style=\"width:700px; height:250px;\"/></a><br>\r\n");
      out.write("<strong class=\"soup2_text\">얼큰한~국물이 땡긴다! 국물맛집</strong>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"seafood\"> \r\n");
      out.write(" <a href=\"seafood.jsp\">\r\n");
      out.write("  <img class=\"seafood2\" alt=\"한정식\"\r\n");
      out.write("  src=\"../food/seafood.jpg\" style=\"width:700px; height:250px;\"/></a><br>\r\n");
      out.write(" <strong class=\"seafood_text\">오늘은 왠지 신선한 해산물이 땡기는걸!</strong>             \r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"meat\"> \r\n");
      out.write(" <a href=\"meat.jsp\">\r\n");
      out.write("  <img class=\"meat2\" alt=\"한정식\"\r\n");
      out.write("  src=\"../food/meat.jpg\" style=\"width:700px; height:250px\"/></a><br>\r\n");
      out.write(" <strong class=\"meat_text\"> 저기압일 때는 고기 앞으로!</strong>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"noodle\"> \r\n");
      out.write(" <a href=\"noodle.jsp\">\r\n");
      out.write("  <img class=\"noodle2\" alt=\"한정식\"\r\n");
      out.write("   src=\"../food/noodle.jpg\" style=\"width:700px; height:250px\"/></a><br>\r\n");
      out.write("   <strong class=\"noodle_text\"> 나는야 면LOVER~</strong> \r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"snack\"> \r\n");
      out.write(" <a href=\"snack.jsp\">\r\n");
      out.write("  <img class=\"snack2\" alt=\"한정식\"\r\n");
      out.write("   src=\"../food/snack.jpg\" style=\"width:700px; height:250px;\"/></a><br> \r\n");
      out.write(" <strong class=\"snack_text\">국민간식 떡볶이가 생각날 땐!</strong>                \r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"title2\"> \r\n");
      out.write(" <hr>\r\n");
      out.write(" <h2>이국적인 음식을 먹어보자</h2>\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"western\">   \r\n");
      out.write(" <a href=\"italian.jsp\">\r\n");
      out.write("  <img class=\"pizza\" alt=\"양식\"\r\n");
      out.write("   src=\"../food/pizza.jpg\" style=\"width:550px; height:250px;\"/></a><br> \r\n");
      out.write("<strong class=\"pizza_text\">쓰빠궤리~앤드 피짜</strong>      \r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"western1\">   \r\n");
      out.write(" <a href=\"hamburger.jsp\">\r\n");
      out.write("  <img class=\"burger\" alt=\"양식\"\r\n");
      out.write("   src=\"../food/burger.jpg\" style=\"width:550px; height:250px;\"/></a><br> \r\n");
      out.write("<strong class=\"burger_text\">수제버거가 먹고싶을 땐 </strong>               \r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"western2\">   \r\n");
      out.write(" <a href=\"french.jsp\">\r\n");
      out.write("  <img class=\"france\" alt=\"양식\"\r\n");
      out.write("   src=\"../food/france.jpg\" style=\"width:550px; height:250px;\"/></a><br> \r\n");
      out.write(" <strong class=\"france_text\">봉쥬르~프랑스음식</strong>                \r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"western3\">   \r\n");
      out.write(" <a href=\"steak.jsp\">\r\n");
      out.write("  <img class=\"steak\" alt=\"양식\"\r\n");
      out.write("   src=\"../food/steak3.jpg\" style=\"width:550px; height:250px;\"/></a><br> \r\n");
      out.write(" <strong class=\"steak_text\">우아하게 고기 한번 썰어보자!</strong>                \r\n");
      out.write(" </div>\r\n");
      out.write("<div class=\"eastern1\"> \r\n");
      out.write("<a href=\"japan.jsp\">\r\n");
      out.write("  <img class=\"sushi\" alt=\"양식\"\r\n");
      out.write("   src=\"../food/sushi.jpg\" style=\"width:550px; height:250px;\"/></a><br> \r\n");
      out.write(" <strong class=\"sushi_text\">곤니찌와! 일본음식</strong>               \r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"eastern2\"> \r\n");
      out.write("<a href=\"chineese.jsp\">\r\n");
      out.write("  <img class=\"china\" alt=\"양식\"\r\n");
      out.write("   src=\"../food/china2.jpg\" style=\"width:550px; height:250px;\"/></a><br> \r\n");
      out.write("  <strong class=\"china_text\">니하오! 중국음식</strong>               \r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"eastern3\"> \r\n");
      out.write("<a href=\"india.jsp\">\r\n");
      out.write("  <img class=\"indo\" alt=\"양식\"\r\n");
      out.write("   src=\"../food/indo.jpg\" style=\"width:550px; height:250px;\"/></a><br> \r\n");
      out.write("  <strong class=\"indo_text\">나마스떼! 인도음식</strong>               \r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"eastern4\"> \r\n");
      out.write("<a href=\"vietfood.jsp\">\r\n");
      out.write("  <img class=\"vietnam\" alt=\"양식\"\r\n");
      out.write("   src=\"../food/vietnam.jpg\" style=\"width:550px; height:250px;\"/></a><br> \r\n");
      out.write(" <strong class=\"vietnam_text\">뜨끈한 쌀국수! 베트남음식</strong>               \r\n");
      out.write("</div>\r\n");
      out.write(" <div class=\"title3\"> \r\n");
      out.write(" <hr>\r\n");
      out.write(" <h2>나는 알콜 free~ 근데 취해! 취하고 싶을 땐</h2>\r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write(" <div class=\"alchol\">   \r\n");
      out.write(" <a href=\"chickenbeer.jsp\">\r\n");
      out.write("  <img class=\"beer\" alt=\"술집\"\r\n");
      out.write("   src=\"../food/beer2.jpg\" style=\"width:550px; height:250px;\"/></a><br> \r\n");
      out.write("<strong class=\"beer_text\">가볍게 맥주 한잔 더 할까?</strong>   \r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write("  <div class=\"alchol1\">   \r\n");
      out.write(" <a href=\"cocktail.jsp\">\r\n");
      out.write("  <img class=\"wine\"  alt=\"술집\"\r\n");
      out.write("   src=\"../food/cocktail.jpg\" style=\"width:550px; height:250px;\"/></a><br> \r\n");
      out.write("<strong class=\"wine_text\">가벼고 달달하게 부담없이 한잔</strong>    \r\n");
      out.write(" </div> \r\n");
      out.write("   <div class=\"alchol2\">   \r\n");
      out.write(" <a href=\"ricewine.jsp\">\r\n");
      out.write("  <img class=\"ricewine\" alt=\"술집\"\r\n");
      out.write("   src=\"../food/rice2.jpg\" style=\"width:550px; height:250px;\"/></a><br> \r\n");
      out.write("<strong class=\"ricewine_text\">막걸리도 나름 매력이 있다구!</strong>    \r\n");
      out.write(" </div> \r\n");
      out.write("   <div class=\"alchol3\">   \r\n");
      out.write(" <a href=\"izakaya.jsp\">\r\n");
      out.write("  <img class=\"sake\" alt=\"술집\"\r\n");
      out.write("   src=\"../food/sake.jpg\" style=\"width:550px; height:250px;\"/></a><br> \r\n");
      out.write("<strong class=\"sake_text\">아기자기하고 이국적인 술집~</strong>\r\n");
      out.write(" </div> \r\n");
      out.write("   <div class=\"alchol4\">   \r\n");
      out.write(" <a href=\"cartbar.jsp\">\r\n");
      out.write("  <img class=\"cartbar\" alt=\"술집\"\r\n");
      out.write("   src=\"../food/cartbar.jpg\" style=\"width:550px; height:250px;\"/></a><br> \r\n");
      out.write(" <strong class=\"cartbar_text\">라떼는~ 옛날 감성 포장마차!</strong> \r\n");
      out.write(" </div> \r\n");
      out.write("   <div class=\"title4\"> \r\n");
      out.write("   <hr>\r\n");
      out.write(" <h2> 밥먹고 맛있는 디저트와 함께 커피 한잔 어때요? 밥배하고 디저트배는 달라요.</h2>\r\n");
      out.write("</div>\r\n");
      out.write("  <div class=\"dessert\">   \r\n");
      out.write(" <a href=\"coffee.jsp\">\r\n");
      out.write("  <img class=\"coffee\"  alt=\"디저트\"\r\n");
      out.write("   src=\"../food/coffee.jpg\" style=\"width:550px; height:250px;\"/></a><br> \r\n");
      out.write(" <strong class=\"coffee_text\"> 저랑 커피 한잔 할래요?</strong>   \r\n");
      out.write(" </div>  \r\n");
      out.write(" \r\n");
      out.write(" <div class=\"dessert1\">   \r\n");
      out.write(" <a href=\"bakery.jsp\">\r\n");
      out.write("  <img class=\"bakery\"  alt=\"디저트\"\r\n");
      out.write("   src=\"../food/bakery.jpg\" style=\"width:550px; height:250px;\"/></a><br> \r\n");
      out.write("<strong class=\"bakery_text\">빵돌이 빵순이를 위한 베이커리</strong>    \r\n");
      out.write(" </div> \r\n");
      out.write("  <div class=\"dessert2\">   \r\n");
      out.write(" <a href=\"icecream.jsp\">\r\n");
      out.write("  <img class=\"icecream\" alt=\"디저트\"\r\n");
      out.write("   src=\"../food/icecream.jpg\" style=\"width:550px; height:250px;\"/></a><br> \r\n");
      out.write("<strong class=\"icecream_text\">시원하고 달콤한 아이스크림~</strong>  \r\n");
      out.write(" </div>	   \r\n");
      out.write("	<div align=\"center\">\r\n");
      out.write("		<footer>\r\n");
      out.write("			<h2>Copyright &copy; 2023 hongminhwa</h2>\r\n");
      out.write("		</footer>\r\n");
      out.write("	</div>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /hyehwaPC/../include/header.jsp(16,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /hyehwaPC/../include/header.jsp(16,2) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/hyehwaPC/../include/header.jsp(16,2) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("   \r\n");
          out.write("    ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("  \r\n");
          out.write("    ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("   ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /hyehwaPC/Index2.jsp(61,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userid == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <!-- 로그인 하지 않은 상태 --> \r\n");
          out.write("  <a href=\"../hyehwa/login.jsp\">로그인</a> |   \r\n");
          out.write("   <button type=\"button\" value=\"회원가입\" id=\"btnCreate\" onclick=\"create()\">회원가입</button>\r\n");
          out.write("   <!-- <button type=\"button\" value=\"회원목록\"  id=\"btnList\" onclick=\"list()\">회원목록</button> -->\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      <!-- 로그인한 상태 -->\r\n");
          out.write("      <h2>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님이 접속중입니다.</h2>\r\n");
          out.write("      ");
          out.write("    \r\n");
          out.write("	  <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/hyehwa_servlet/view.do?userid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">회원정보수정</a>\r\n");
          out.write("         <button type=\"button\" id=\"btnLogout\">로그아웃</button>\r\n");
          out.write("         <button type=\"button\" value=\"회원목록\"  id=\"btnList\" onclick=\"list()\">회원목록</button>\r\n");
          out.write("       \r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
