/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-05-01 12:00:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hyehwaPC;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinhyehwa_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"./hyehwajsp/join_style.css\">   -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css\" />\r\n");
      out.write("<!-- <script src=\"https://code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"../include/jquery-3.6.3.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".title {\r\n");
      out.write("  margin-top: 90px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  font-weight: 600\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #F5FFFA;\r\n");
      out.write("}\r\n");
      out.write(".home h2{\r\n");
      out.write("	margin-top: 70px;\r\n");
      out.write("	text-align: center; \r\n");
      out.write("	font-family: brush script mt;\r\n");
      out.write(" 	color:blue;\r\n");
      out.write("}\r\n");
      out.write(".home a{\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function() {\r\n");
      out.write("	list(); \r\n");
      out.write("	$(\"#btnSave\").click(function() {\r\n");
      out.write("		 insert(); \r\n");
      out.write("		 alert(\"회원가입에 성공했습니다. 아이디와 비밀번호로 다시 로그인해주세요\")\r\n");
      out.write("		location.href=\"../hyehwa/login.jsp\";\r\n");
      out.write("	\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function insert() {\r\n");
      out.write("	var param=\"userid=\"+ $(\"#userid\").val()\r\n");
      out.write("	+\"&passwd=\"+$(\"#passwd\").val()\r\n");
      out.write("	+\"&name=\"+$(\"#name\").val()\r\n");
      out.write("	+\"&email=\"+$(\"#email\").val()\r\n");
      out.write("	+\"&hp=\"+$(\"#hp\").val()\r\n");
      out.write("	+\"&address1=\"+$(\"#address1\").val()\r\n");
      out.write("	+\"&address2=\"+$(\"#address2\").val();\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type: \"post\",\r\n");
      out.write("		url: \"/jsp02/hyehwa_servlet/join.do\", \r\n");
      out.write("		data : param, \r\n");
      out.write("		success : function(){\r\n");
      out.write("			list(); //회원목록 자동 갱신 코드 \r\n");
      out.write("			//입력값 초기화. \r\n");
      out.write("			$(\"#userid\").val(\"\");\r\n");
      out.write("			$(\"#passwd\").val(\"\"); \r\n");
      out.write("			$(\"#name\").val(\"\");\r\n");
      out.write("			$(\"#email\").val(\"\"); \r\n");
      out.write("			$(\"#hp\").val(\"\"); \r\n");
      out.write("			$(\"#address1\").val(\"\"); \r\n");
      out.write("			$(\"#address2\").val(\"\");\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function list() {\r\n");
      out.write("	$.ajax({  \r\n");
      out.write("		type:\"post\",\r\n");
      out.write("		url:\"/jsp02/hyehwa_servlet/list.do\",\r\n");
      out.write("		success: function(result) {\r\n");
      out.write("			console.log(result);\r\n");
      out.write("			$(\"#memberlist\").html(result); \r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"home\"> \r\n");
      out.write("<h2 style=\"font-size: 100px;\"><a href=\"../hyehwaPC/Index2.jsp\">hyehwaPlate</a></h2><br><br>\r\n");
      out.write("<hr> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<span style=\"padding-left: 125px; font-size: 10px\"> </span>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\"> \r\n");
      out.write("<h2>로그인</h2>\r\n");
      out.write("<form name=\"form1\" method=\"post\"> \r\n");
      out.write("<table border=\"1\" style=\"width: 100%;\"> \r\n");
      out.write(" <tr> \r\n");
      out.write("    <td>아이디</td> \r\n");
      out.write("    <td><input type=\"text\" size=\"32\" id=\"userid\"></td>\r\n");
      out.write(" </tr> \r\n");
      out.write(" <tr>\r\n");
      out.write("   <td>비밀번호</td>\r\n");
      out.write("   <td><input type=\"password\" class=\"check1\" size=\"32\" id= \"passwd\"></td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("   <td>이름</td>\r\n");
      out.write("   <td><input id=\"name\"> </td>\r\n");
      out.write(" </tr> \r\n");
      out.write("  <tr>\r\n");
      out.write("   <td>핸드폰번호</td>\r\n");
      out.write("   <td><input type=\"tel\" pattern=\"(010)-\\d{3,4}-\\d{4}\" name=\"tel\" title=\"010-####-####\" required=\"required\" size=\"32\" id=\"hp\"></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("   <td>이메일</td>\r\n");
      out.write("    <td><input type=\"text\" class=\"check3\" size=\"10\" id=\"email\" placeholder=\"abc@abc.com\"></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td>기본주소</td>\r\n");
      out.write("    <td><input type=\"text\" size=\"32\" id=\"address2\" placeholder=\"상세주소\"></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("    <tr> \r\n");
      out.write("      <td colspan=\"2\" align=\"center\"> \r\n");
      out.write("        <button type=\"button\" id=\"btnSave\" style=\"text-align:right;\"> 회원가입</button>        \r\n");
      out.write("    </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"memberList\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
