/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-04-17 10:26:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hyehwaPC;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1678344190252L));
    _jspx_dependants.put("jar:file:/C:/work_javaKH/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jsp02/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/hyehwaPC/../include/header.jsp", Long.valueOf(1679567087703L));
    _jspx_dependants.put("jar:file:/C:/work_javaKH/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jsp02/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/work_javaKH/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jsp02/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"../include/jquery-3.6.3.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("1) jstl (jsp standard Tag Library, jsp 표준 태그 라이브러리 \r\n");
      out.write("2) jstl 사용 이유: model1은 jsp페이지 중심, model2는 java코드 중심, jsp웹페이지에서 \r\n");
      out.write("java코드를 안쓸 수는 없지만 이를 최소화 하기 위해서 jstl과 EL기법을 씀, \r\n");
      out.write("복잡한 자바코드를 대체하기 위한 태그 \r\n");
      out.write("3) taglib uri=\"태그라이브러리의 식별자=\" prefix=\"태그 접두어\" \r\n");
      out.write("4) Core tag(핵심태그, 제일 자주 사용되는 태그들) \r\n");
      out.write("  -->\r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/jquery-3.6.3.min.js\"></script>\r\n");
      out.write("   <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/js/bootstrap.js\"></script>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/css/bootstrap.css\">\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <ul class=\"list-restaurants type-single-big top_list_restaurant_list\">\r\n");
      out.write("              <li class=\"toplist_list\">\r\n");
      out.write("                <div class=\"with-review\">\r\n");
      out.write("                  <figure class=\"restaurant-item\">\r\n");
      out.write("                    <a href=\"/restaurants/RxFRdDnCfIGs\"\r\n");
      out.write("                      onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:0,&quot;restaurant_key&quot;:&quot;RxFRdDnCfIGs&quot;})\">\r\n");
      out.write("                      <div class=\"thumb\">\r\n");
      out.write("                        <img class=\"center-croping lazy\"\r\n");
      out.write("                             alt=\"칸다소바 사진 - 서울특별시 송파구 올림픽로 300 롯데월드몰 캐주얼동 6F\"\r\n");
      out.write("                             data-original=\"https://mp-seoul-image-production-s3.mangoplate.com/535867_1677574550126157.jpg?fit=around|738:738&amp;crop=738:738;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/kssf5eveeva_xlmy.jpg?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                          />\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption>\r\n");
      out.write("                      <div class=\"info\">\r\n");
      out.write("                        <div class=\"wannago_wrap\">\r\n");
      out.write("                          <button class=\"btn-type-icon favorite wannago_btn \"\r\n");
      out.write("                                  data-restaurant_uuid=\"492453\"\r\n");
      out.write("                                  data-action_id=\"\">\r\n");
      out.write("                          </button>\r\n");
      out.write("                          <p class=\"wannago_txt\">가고싶다 </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"title \">\r\n");
      out.write("                          <a href=\"/restaurants/RxFRdDnCfIGs\"\r\n");
      out.write("                             onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:0,&quot;restaurant_key&quot;:&quot;RxFRdDnCfIGs&quot;})\">\r\n");
      out.write("                            1.<h3> 칸다소바</h3>\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <strong class=\"point  \">\r\n");
      out.write("                          <span>4.7</span>\r\n");
      out.write("                        </strong>\r\n");
      out.write("                        <p class=\"etc \">서울특별시 송파구 올림픽로 300 롯데월드몰 캐주얼동 6F</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                  </figure>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"review-content no-bottom\">\r\n");
      out.write("                      <figure class=\"user\">\r\n");
      out.write("                        <div class=\"thumb lazy\"\r\n");
      out.write("                             data-original=\"https://s3-ap-northeast-2.amazonaws.com/mp-seoul-image-production/1163316_1660570058865?fit=around|56:56&amp;crop=56:56;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/jmcmlp180qwkp1jj.png?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <figcaption class=\"\">\r\n");
      out.write("                          SKang\r\n");
      out.write("                        </figcaption>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                      <p class=\"short_review \" onclick=\"trackEvent('CLICK_FEATURED_REVIEW')\" data-restaurant_key=\"RxFRdDnCfIGs\" data-is_long_reivew=\"\r\n");
      out.write("                        true\r\n");
      out.write("                        \">\r\n");
      out.write("                           대표메뉴인 마제소바와 아부라소바를 각각 주문해서, 깨끗하게 바닥까지 보고 왔다. 맛은 상당히 새롭고 신기했다. 마제소바는 뭔가 먹어본듯 하면서...\r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                      <p class=\"long_review \">\r\n");
      out.write("                         대표메뉴인 마제소바와 아부라소바를 각각 주문해서, 깨끗하게 바닥까지 보고 왔다. 맛은 상당히 새롭고 신기했다. 마제소바는 뭔가 먹어본듯 하면서도 새로운 맛이 재밌었고, 아부라소바는 엄청나게 들어간 파의 비쥬얼과 달리 고소하면서 담백한 맛이 느껴졌다. 특히 면이 정말 탱탱해서, 면치기에 자신 좀 있다-하시는 분들은 후루룩 먹는 재미도 클 듯. \r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                        <span class=\"review_more_btn\" onclick=\"trackEvent('CLICK_MORE_REVIEW', {&quot;position&quot;:0,&quot;restaurant_key&quot;:&quot;RxFRdDnCfIGs&quot;})\">더보기</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <a href=\"/restaurants/RxFRdDnCfIGs\" class=\"btn-detail\"\r\n");
      out.write("                     onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:0,&quot;restaurant_key&quot;:&quot;RxFRdDnCfIGs&quot;})\">\r\n");
      out.write("                      <div class=\"restaurant-more-name\">칸다소바</div>\r\n");
      out.write("                      <div class=\"restaurant-more-text\">더보기 ></div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"toplist_list\">\r\n");
      out.write("                <div class=\"with-review\">\r\n");
      out.write("                  <figure class=\"restaurant-item\">\r\n");
      out.write("                    <a href=\"/restaurants/vI2c9_tWVwoc\"\r\n");
      out.write("                      onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:1,&quot;restaurant_key&quot;:&quot;vI2c9_tWVwoc&quot;})\">\r\n");
      out.write("                      <div class=\"thumb\">\r\n");
      out.write("                        <img class=\"center-croping lazy\"\r\n");
      out.write("                             alt=\"엘리스리틀이태리 사진 - 서울특별시 송파구 백제고분로41길 43-21 SANDONG빌딩\"\r\n");
      out.write("                             data-original=\"https://mp-seoul-image-production-s3.mangoplate.com/254511/449685_1674122136234_60945?fit=around|738:738&amp;crop=738:738;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/kssf5eveeva_xlmy.jpg?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                          />\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption>\r\n");
      out.write("                      <div class=\"info\">\r\n");
      out.write("                        <div class=\"wannago_wrap\">\r\n");
      out.write("                          <button class=\"btn-type-icon favorite wannago_btn \"\r\n");
      out.write("                                  data-restaurant_uuid=\"254511\"\r\n");
      out.write("                                  data-action_id=\"\">\r\n");
      out.write("                          </button>\r\n");
      out.write("                          <p class=\"wannago_txt\">가고싶다 </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"title \">\r\n");
      out.write("                          <a href=\"/restaurants/vI2c9_tWVwoc\"\r\n");
      out.write("                             onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:1,&quot;restaurant_key&quot;:&quot;vI2c9_tWVwoc&quot;})\">\r\n");
      out.write("                            2.<h3> 엘리스리틀이태리</h3>\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <strong class=\"point  \">\r\n");
      out.write("                          <span>4.4</span>\r\n");
      out.write("                        </strong>\r\n");
      out.write("                        <p class=\"etc \">서울특별시 송파구 백제고분로41길 43-21 SANDONG빌딩</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                  </figure>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"review-content no-bottom\">\r\n");
      out.write("                      <figure class=\"user\">\r\n");
      out.write("                        <div class=\"thumb lazy\"\r\n");
      out.write("                             data-original=\"https://s3-ap-northeast-2.amazonaws.com/mp-seoul-image-production/449685_1659177131334?fit=around|56:56&amp;crop=56:56;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/jmcmlp180qwkp1jj.png?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <figcaption class=\"\">\r\n");
      out.write("                          YNZ\r\n");
      out.write("                        </figcaption>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                      <p class=\"short_review \" onclick=\"trackEvent('CLICK_FEATURED_REVIEW')\" data-restaurant_key=\"vI2c9_tWVwoc\" data-is_long_reivew=\"\r\n");
      out.write("                        true\r\n");
      out.write("                        \">\r\n");
      out.write("                          식전빵으로는 피자 도우를 조금 떼어내 구운 빵이 나오고, 웰컴 푸드로 아란치니가 나왔다. 아란치니가 맛있어서 즉각 기대감 상승. 다행히 파스타도...\r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                      <p class=\"long_review \">\r\n");
      out.write("                        식전빵으로는 피자 도우를 조금 떼어내 구운 빵이 나오고, 웰컴 푸드로 아란치니가 나왔다. 아란치니가 맛있어서 즉각 기대감 상승. 다행히 파스타도 기대를 저버리지 않고 맛있었다. 어란 파스타는 적당히 짭조름하면서 고소하고 어란향이 낭낭하다. 로제파스타도 성공적.\r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                        <span class=\"review_more_btn\" onclick=\"trackEvent('CLICK_MORE_REVIEW', {&quot;position&quot;:1,&quot;restaurant_key&quot;:&quot;vI2c9_tWVwoc&quot;})\">더보기</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <a href=\"/restaurants/vI2c9_tWVwoc\" class=\"btn-detail\"\r\n");
      out.write("                     onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:1,&quot;restaurant_key&quot;:&quot;vI2c9_tWVwoc&quot;})\">\r\n");
      out.write("                      <div class=\"restaurant-more-name\">엘리스리틀이태리</div>\r\n");
      out.write("                      <div class=\"restaurant-more-text\">더보기 ></div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"toplist_list\">\r\n");
      out.write("                <div class=\"with-review\">\r\n");
      out.write("                  <figure class=\"restaurant-item\">\r\n");
      out.write("                    <a href=\"/restaurants/H6EKPX1ASO\"\r\n");
      out.write("                      onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:2,&quot;restaurant_key&quot;:&quot;H6EKPX1ASO&quot;})\">\r\n");
      out.write("                      <div class=\"thumb\">\r\n");
      out.write("                        <img class=\"center-croping lazy\"\r\n");
      out.write("                             alt=\"뉴질랜드스토리 사진 - 서울특별시 송파구 석촌호수로 268 경남레이크파크 113호\"\r\n");
      out.write("                             data-original=\"https://mp-seoul-image-production-s3.mangoplate.com/56239/825389_1669799591169_19720?fit=around|738:738&amp;crop=738:738;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/kssf5eveeva_xlmy.jpg?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                          />\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption>\r\n");
      out.write("                      <div class=\"info\">\r\n");
      out.write("                        <div class=\"wannago_wrap\">\r\n");
      out.write("                          <button class=\"btn-type-icon favorite wannago_btn \"\r\n");
      out.write("                                  data-restaurant_uuid=\"56239\"\r\n");
      out.write("                                  data-action_id=\"\">\r\n");
      out.write("                          </button>\r\n");
      out.write("                          <p class=\"wannago_txt\">가고싶다 </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"title \">\r\n");
      out.write("                          <a href=\"/restaurants/H6EKPX1ASO\"\r\n");
      out.write("                             onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:2,&quot;restaurant_key&quot;:&quot;H6EKPX1ASO&quot;})\">\r\n");
      out.write("                            3.<h3> 뉴질랜드스토리</h3>\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <strong class=\"point  \">\r\n");
      out.write("                          <span>4.4</span>\r\n");
      out.write("                        </strong>\r\n");
      out.write("                        <p class=\"etc \">서울특별시 송파구 석촌호수로 268 경남레이크파크 113호</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                  </figure>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"review-content no-bottom\">\r\n");
      out.write("                      <figure class=\"user\">\r\n");
      out.write("                        <div class=\"thumb lazy\"\r\n");
      out.write("                             data-original=\"https://s3-ap-northeast-2.amazonaws.com/mp-seoul-image-production/825389_1631869933590?fit=around|56:56&amp;crop=56:56;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/jmcmlp180qwkp1jj.png?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <figcaption class=\"\">\r\n");
      out.write("                          왕십리탈출러\r\n");
      out.write("                        </figcaption>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                      <p class=\"short_review \" onclick=\"trackEvent('CLICK_FEATURED_REVIEW')\" data-restaurant_key=\"H6EKPX1ASO\" data-is_long_reivew=\"\r\n");
      out.write("                        true\r\n");
      out.write("                        \">\r\n");
      out.write("                          석촌호수 근처에 있는 굉장히 핫한 샌드위치집. 가게 자체는 굉장히 아담하고 분위기 자체가 뉴질랜드스러운 분위기이다. 내 입맛에는 크림치킨이 들어...\r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                      <p class=\"long_review \">\r\n");
      out.write("                        석촌호수 근처에 있는 굉장히 핫한 샌드위치집. 가게 자체는 굉장히 아담하고 분위기 자체가 뉴질랜드스러운 분위기이다. 내 입맛에는 크림치킨이 들어간 샌드위치가 제일 맛있었다. 제일 식사에 비슷한 느낌이랄까? 블루베리가 들어간 샌드위치는 달달한 맛이 있다 보니 커피랑 어울리는 느낌이었다. \r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                        <span class=\"review_more_btn\" onclick=\"trackEvent('CLICK_MORE_REVIEW', {&quot;position&quot;:2,&quot;restaurant_key&quot;:&quot;H6EKPX1ASO&quot;})\">더보기</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <a href=\"/restaurants/H6EKPX1ASO\" class=\"btn-detail\"\r\n");
      out.write("                     onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:2,&quot;restaurant_key&quot;:&quot;H6EKPX1ASO&quot;})\">\r\n");
      out.write("                      <div class=\"restaurant-more-name\">뉴질랜드스토리</div>\r\n");
      out.write("                      <div class=\"restaurant-more-text\">더보기 ></div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"toplist_list\">\r\n");
      out.write("                <div class=\"with-review\">\r\n");
      out.write("                  <figure class=\"restaurant-item\">\r\n");
      out.write("                    <a href=\"/restaurants/KCcUzsJWALdw\"\r\n");
      out.write("                      onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:3,&quot;restaurant_key&quot;:&quot;KCcUzsJWALdw&quot;})\">\r\n");
      out.write("                      <div class=\"thumb\">\r\n");
      out.write("                        <img class=\"center-croping lazy\"\r\n");
      out.write("                             alt=\"디저티스트 사진 - 서울특별시 송파구 송파대로48길 37 호수임광아파트 상가동 2F\"\r\n");
      out.write("                             data-original=\"https://mp-seoul-image-production-s3.mangoplate.com/806208_1679306914584340.jpg?fit=around|738:738&amp;crop=738:738;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/kssf5eveeva_xlmy.jpg?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                          />\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption>\r\n");
      out.write("                      <div class=\"info\">\r\n");
      out.write("                        <div class=\"wannago_wrap\">\r\n");
      out.write("                          <button class=\"btn-type-icon favorite wannago_btn \"\r\n");
      out.write("                                  data-restaurant_uuid=\"407393\"\r\n");
      out.write("                                  data-action_id=\"\">\r\n");
      out.write("                          </button>\r\n");
      out.write("                          <p class=\"wannago_txt\">가고싶다 </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"title \">\r\n");
      out.write("                          <a href=\"/restaurants/KCcUzsJWALdw\"\r\n");
      out.write("                             onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:3,&quot;restaurant_key&quot;:&quot;KCcUzsJWALdw&quot;})\">\r\n");
      out.write("                            4.<h3> 디저티스트</h3>\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <strong class=\"point  \">\r\n");
      out.write("                          <span>4.4</span>\r\n");
      out.write("                        </strong>\r\n");
      out.write("                        <p class=\"etc \">서울특별시 송파구 송파대로48길 37 호수임광아파트 상가동 2F</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                  </figure>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"review-content no-bottom\">\r\n");
      out.write("                      <figure class=\"user\">\r\n");
      out.write("                        <div class=\"thumb lazy\"\r\n");
      out.write("                             data-original=\"https://mp-seoul-image-production-s3.mangoplate.com/806208_1544812105714?fit=around|56:56&amp;crop=56:56;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/jmcmlp180qwkp1jj.png?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <figcaption class=\"\">\r\n");
      out.write("                          라떼라테\r\n");
      out.write("                        </figcaption>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                      <p class=\"short_review \" onclick=\"trackEvent('CLICK_FEATURED_REVIEW')\" data-restaurant_key=\"KCcUzsJWALdw\" data-is_long_reivew=\"\r\n");
      out.write("                        true\r\n");
      out.write("                        \">\r\n");
      out.write("                          케이크랑 파르페 사이에서 고민하다가 파르페를 시켰는데, 후회 없는 선택이었습니다. 우와아아 파르페 진짜 맛있어요... 바닐라 젤라또와 라즈베리맛...\r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                      <p class=\"long_review \">\r\n");
      out.write("                        케이크랑 파르페 사이에서 고민하다가 파르페를 시켰는데, 후회 없는 선택이었습니다. 우와아아 파르페 진짜 맛있어요... 바닐라 젤라또와 라즈베리맛 셔벗을 지나면 나오는 진득한 초코 젤라또~ 녹진하게 녹은 아이스크림이 딸기랑 정말 잘어울려요. 맨 아래 층에는 진한 크림치즈랑 비스킷, 딸기맛 젤리가 있어요! 셋을 같이 퍼먹으니까 무스타르트를 먹는 것 같았어요. \r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                        <span class=\"review_more_btn\" onclick=\"trackEvent('CLICK_MORE_REVIEW', {&quot;position&quot;:3,&quot;restaurant_key&quot;:&quot;KCcUzsJWALdw&quot;})\">더보기</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <a href=\"/restaurants/KCcUzsJWALdw\" class=\"btn-detail\"\r\n");
      out.write("                     onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:3,&quot;restaurant_key&quot;:&quot;KCcUzsJWALdw&quot;})\">\r\n");
      out.write("                      <div class=\"restaurant-more-name\">디저티스트</div>\r\n");
      out.write("                      <div class=\"restaurant-more-text\">더보기 ></div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"toplist_list\">\r\n");
      out.write("                <div class=\"with-review\">\r\n");
      out.write("                  <figure class=\"restaurant-item\">\r\n");
      out.write("                    <a href=\"/restaurants/iHsjMVHB3Ahb\"\r\n");
      out.write("                      onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:4,&quot;restaurant_key&quot;:&quot;iHsjMVHB3Ahb&quot;})\">\r\n");
      out.write("                      <div class=\"thumb\">\r\n");
      out.write("                        <img class=\"center-croping lazy\"\r\n");
      out.write("                             alt=\"해목 사진 - 서울특별시 송파구 올림픽로 300  롯데월드몰 6F\"\r\n");
      out.write("                             data-original=\"https://mp-seoul-image-production-s3.mangoplate.com/492372/60039_1670407107362_1000007744?fit=around|738:738&amp;crop=738:738;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/kssf5eveeva_xlmy.jpg?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                          />\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption>\r\n");
      out.write("                      <div class=\"info\">\r\n");
      out.write("                        <div class=\"wannago_wrap\">\r\n");
      out.write("                          <button class=\"btn-type-icon favorite wannago_btn \"\r\n");
      out.write("                                  data-restaurant_uuid=\"492372\"\r\n");
      out.write("                                  data-action_id=\"\">\r\n");
      out.write("                          </button>\r\n");
      out.write("                          <p class=\"wannago_txt\">가고싶다 </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"title \">\r\n");
      out.write("                          <a href=\"/restaurants/iHsjMVHB3Ahb\"\r\n");
      out.write("                             onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:4,&quot;restaurant_key&quot;:&quot;iHsjMVHB3Ahb&quot;})\">\r\n");
      out.write("                            5.<h3> 해목</h3>\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <strong class=\"point  \">\r\n");
      out.write("                          <span>4.4</span>\r\n");
      out.write("                        </strong>\r\n");
      out.write("                        <p class=\"etc \">서울특별시 송파구 올림픽로 300  롯데월드몰 6F</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                  </figure>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"review-content no-bottom\">\r\n");
      out.write("                      <figure class=\"user\">\r\n");
      out.write("                        <div class=\"thumb lazy\"\r\n");
      out.write("                             data-original=\"https://s3-ap-northeast-2.amazonaws.com/mp-seoul-image-production/511866_1676988335093?fit=around|56:56&amp;crop=56:56;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/jmcmlp180qwkp1jj.png?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <figcaption class=\"\">\r\n");
      out.write("                          림\r\n");
      out.write("                        </figcaption>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                      <p class=\"short_review \" onclick=\"trackEvent('CLICK_FEATURED_REVIEW')\" data-restaurant_key=\"iHsjMVHB3Ahb\" data-is_long_reivew=\"\r\n");
      out.write("                        true\r\n");
      out.write("                        \">\r\n");
      out.write("                          이제는 서울에서도 굳이 부산까지 가지 않아도 맛있는 히츠마부시를 맛볼 수 있는 곳이 제법 많아졌다. 부산 매장 같이 현지 분위기 물씬나는 인테리...\r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                      <p class=\"long_review \">\r\n");
      out.write("                        이제는 서울에서도 굳이 부산까지 가지 않아도 맛있는 히츠마부시를 맛볼 수 있는 곳이 제법 많아졌다. 부산 매장 같이 현지 분위기 물씬나는 인테리어가 예쁘다. 역시 기대만큼 맛있었는데 나는 역시 마지막에 녹차를 부어 마시는 게 가장 맛있는 듯! 일하는 직원들이 적지 않아서 응대가 빠른 편인 게 좋았다.\r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                        <span class=\"review_more_btn\" onclick=\"trackEvent('CLICK_MORE_REVIEW', {&quot;position&quot;:4,&quot;restaurant_key&quot;:&quot;iHsjMVHB3Ahb&quot;})\">더보기</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <a href=\"/restaurants/iHsjMVHB3Ahb\" class=\"btn-detail\"\r\n");
      out.write("                     onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:4,&quot;restaurant_key&quot;:&quot;iHsjMVHB3Ahb&quot;})\">\r\n");
      out.write("                      <div class=\"restaurant-more-name\">해목</div>\r\n");
      out.write("                      <div class=\"restaurant-more-text\">더보기 ></div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"toplist_list\">\r\n");
      out.write("                <div class=\"with-review\">\r\n");
      out.write("                  <figure class=\"restaurant-item\">\r\n");
      out.write("                    <a href=\"/restaurants/ztTTr81jaBm7\"\r\n");
      out.write("                      onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:5,&quot;restaurant_key&quot;:&quot;ztTTr81jaBm7&quot;})\">\r\n");
      out.write("                      <div class=\"thumb\">\r\n");
      out.write("                        <img class=\"center-croping lazy\"\r\n");
      out.write("                             alt=\"미엔아이 사진 - 서울특별시 송파구 오금로16길 5 1F\"\r\n");
      out.write("                             data-original=\"https://mp-seoul-image-production-s3.mangoplate.com/440625_1677592733735829.jpg?fit=around|738:738&amp;crop=738:738;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/kssf5eveeva_xlmy.jpg?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                          />\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption>\r\n");
      out.write("                      <div class=\"info\">\r\n");
      out.write("                        <div class=\"wannago_wrap\">\r\n");
      out.write("                          <button class=\"btn-type-icon favorite wannago_btn \"\r\n");
      out.write("                                  data-restaurant_uuid=\"345079\"\r\n");
      out.write("                                  data-action_id=\"\">\r\n");
      out.write("                          </button>\r\n");
      out.write("                          <p class=\"wannago_txt\">가고싶다 </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"title \">\r\n");
      out.write("                          <a href=\"/restaurants/ztTTr81jaBm7\"\r\n");
      out.write("                             onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:5,&quot;restaurant_key&quot;:&quot;ztTTr81jaBm7&quot;})\">\r\n");
      out.write("                            6.<h3> 미엔아이</h3>\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <strong class=\"point  \">\r\n");
      out.write("                          <span>4.3</span>\r\n");
      out.write("                        </strong>\r\n");
      out.write("                        <p class=\"etc \">서울특별시 송파구 오금로16길 5 1F</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                  </figure>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"review-content no-bottom\">\r\n");
      out.write("                      <figure class=\"user\">\r\n");
      out.write("                        <div class=\"thumb lazy\"\r\n");
      out.write("                             data-original=\"https://s3-ap-northeast-2.amazonaws.com/mp-seoul-image-production/440625_1636609351623?fit=around|56:56&amp;crop=56:56;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/jmcmlp180qwkp1jj.png?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <figcaption class=\"\">\r\n");
      out.write("                          보경\r\n");
      out.write("                        </figcaption>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                      <p class=\"short_review \" onclick=\"trackEvent('CLICK_FEATURED_REVIEW')\" data-restaurant_key=\"ztTTr81jaBm7\" data-is_long_reivew=\"\r\n");
      out.write("                        true\r\n");
      out.write("                        \">\r\n");
      out.write("                          간장 향이 잘 살아있는 깔끔한 우육면. 우육면, 굉장히 맛있다. 부드럽게 씹히는 고기에다가 적절한 간의 국물. 우육면관은 깊은 육향이 베어있는 ...\r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                      <p class=\"long_review \">\r\n");
      out.write("                        간장 향이 잘 살아있는 깔끔한 우육면. 우육면, 굉장히 맛있다. 부드럽게 씹히는 고기에다가 적절한 간의 국물. 우육면관은 깊은 육향이 베어있는 맑은 마무리감의 국물이 특징이라면, 이 곳 국물은 간장 향이 깔끔하게 베어있는게 특징이다. 호록호록 입안으로 기분좋게 들어오는 면 질감도 아주 좋았다. \r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                        <span class=\"review_more_btn\" onclick=\"trackEvent('CLICK_MORE_REVIEW', {&quot;position&quot;:5,&quot;restaurant_key&quot;:&quot;ztTTr81jaBm7&quot;})\">더보기</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <a href=\"/restaurants/ztTTr81jaBm7\" class=\"btn-detail\"\r\n");
      out.write("                     onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:5,&quot;restaurant_key&quot;:&quot;ztTTr81jaBm7&quot;})\">\r\n");
      out.write("                      <div class=\"restaurant-more-name\">미엔아이</div>\r\n");
      out.write("                      <div class=\"restaurant-more-text\">더보기 ></div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"toplist_list\">\r\n");
      out.write("                <div class=\"with-review\">\r\n");
      out.write("                  <figure class=\"restaurant-item\">\r\n");
      out.write("                    <a href=\"/restaurants/Hps9zhInl69-\"\r\n");
      out.write("                      onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:6,&quot;restaurant_key&quot;:&quot;Hps9zhInl69-&quot;})\">\r\n");
      out.write("                      <div class=\"thumb\">\r\n");
      out.write("                        <img class=\"center-croping lazy\"\r\n");
      out.write("                             alt=\"야끼소바니주마루 사진 - 서울특별시 송파구 백제고분로41길 21 1F\"\r\n");
      out.write("                             data-original=\"https://mp-seoul-image-production-s3.mangoplate.com/364240/1289221_1562810249067_51494?fit=around|738:738&amp;crop=738:738;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/kssf5eveeva_xlmy.jpg?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                          />\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption>\r\n");
      out.write("                      <div class=\"info\">\r\n");
      out.write("                        <div class=\"wannago_wrap\">\r\n");
      out.write("                          <button class=\"btn-type-icon favorite wannago_btn \"\r\n");
      out.write("                                  data-restaurant_uuid=\"364240\"\r\n");
      out.write("                                  data-action_id=\"\">\r\n");
      out.write("                          </button>\r\n");
      out.write("                          <p class=\"wannago_txt\">가고싶다 </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"title \">\r\n");
      out.write("                          <a href=\"/restaurants/Hps9zhInl69-\"\r\n");
      out.write("                             onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:6,&quot;restaurant_key&quot;:&quot;Hps9zhInl69-&quot;})\">\r\n");
      out.write("                            7.<h3> 야끼소바니주마루</h3>\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <strong class=\"point  \">\r\n");
      out.write("                          <span>4.3</span>\r\n");
      out.write("                        </strong>\r\n");
      out.write("                        <p class=\"etc \">서울특별시 송파구 백제고분로41길 21 1F</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                  </figure>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"review-content no-bottom\">\r\n");
      out.write("                      <figure class=\"user\">\r\n");
      out.write("                        <div class=\"thumb lazy\"\r\n");
      out.write("                             data-original=\"https://s3-ap-northeast-2.amazonaws.com/mp-seoul-image-production/586167_1677732216003?fit=around|56:56&amp;crop=56:56;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/jmcmlp180qwkp1jj.png?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <figcaption class=\"\">\r\n");
      out.write("                          Rachel\r\n");
      out.write("                        </figcaption>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                      <p class=\"short_review \" onclick=\"trackEvent('CLICK_FEATURED_REVIEW')\" data-restaurant_key=\"Hps9zhInl69-\" data-is_long_reivew=\"\r\n");
      out.write("                        true\r\n");
      out.write("                        \">\r\n");
      out.write("                          아주아주 맛있는 야끼소바 전문점. 면도 직접 제면하시는데 약간 탄력있고 우동보다는 얇은 면이다. 소스야끼소바보다는 소금간을 한 시오야끼소바를 추...\r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                      <p class=\"long_review \">\r\n");
      out.write("                        아주아주 맛있는 야끼소바 전문점. 면도 직접 제면하시는데 약간 탄력있고 우동보다는 얇은 면이다. 소스야끼소바보다는 소금간을 한 시오야끼소바를 추천한다. 소스보다 슴슴할 것 같은데 오히려 그보다는더 감칠맛과 풍미가 느껴지는 맛이다. 야끼소바의 알리오올리오버전이라고 생각하면 될 것 같다. 하이볼도 굉장히 맛있는데 일본 위스키 중 마르스 라는 위스키를 사용하신다고. \r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                        <span class=\"review_more_btn\" onclick=\"trackEvent('CLICK_MORE_REVIEW', {&quot;position&quot;:6,&quot;restaurant_key&quot;:&quot;Hps9zhInl69-&quot;})\">더보기</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <a href=\"/restaurants/Hps9zhInl69-\" class=\"btn-detail\"\r\n");
      out.write("                     onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:6,&quot;restaurant_key&quot;:&quot;Hps9zhInl69-&quot;})\">\r\n");
      out.write("                      <div class=\"restaurant-more-name\">야끼소바니주마루</div>\r\n");
      out.write("                      <div class=\"restaurant-more-text\">더보기 ></div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"toplist_list\">\r\n");
      out.write("                <div class=\"with-review\">\r\n");
      out.write("                  <figure class=\"restaurant-item\">\r\n");
      out.write("                    <a href=\"/restaurants/-jjalqkpiLPa\"\r\n");
      out.write("                      onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:7,&quot;restaurant_key&quot;:&quot;-jjalqkpiLPa&quot;})\">\r\n");
      out.write("                      <div class=\"thumb\">\r\n");
      out.write("                        <img class=\"center-croping lazy\"\r\n");
      out.write("                             alt=\"다운타우너 사진 - 서울특별시 송파구 백제고분로45길 3 1F\"\r\n");
      out.write("                             data-original=\"https://mp-seoul-image-production-s3.mangoplate.com/349798/1289221_1618087744251_9673?fit=around|738:738&amp;crop=738:738;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/kssf5eveeva_xlmy.jpg?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                          />\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption>\r\n");
      out.write("                      <div class=\"info\">\r\n");
      out.write("                        <div class=\"wannago_wrap\">\r\n");
      out.write("                          <button class=\"btn-type-icon favorite wannago_btn \"\r\n");
      out.write("                                  data-restaurant_uuid=\"349798\"\r\n");
      out.write("                                  data-action_id=\"\">\r\n");
      out.write("                          </button>\r\n");
      out.write("                          <p class=\"wannago_txt\">가고싶다 </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"title \">\r\n");
      out.write("                          <a href=\"/restaurants/-jjalqkpiLPa\"\r\n");
      out.write("                             onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:7,&quot;restaurant_key&quot;:&quot;-jjalqkpiLPa&quot;})\">\r\n");
      out.write("                            8.<h3> 다운타우너</h3>\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <strong class=\"point  \">\r\n");
      out.write("                          <span>4.3</span>\r\n");
      out.write("                        </strong>\r\n");
      out.write("                        <p class=\"etc \">서울특별시 송파구 백제고분로45길 3 1F</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                  </figure>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"review-content no-bottom\">\r\n");
      out.write("                      <figure class=\"user\">\r\n");
      out.write("                        <div class=\"thumb lazy\"\r\n");
      out.write("                             data-original=\"https://s3-ap-northeast-2.amazonaws.com/mp-seoul-image-production/1847477_1664593710804?fit=around|56:56&amp;crop=56:56;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/jmcmlp180qwkp1jj.png?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <figcaption class=\"\">\r\n");
      out.write("                          빵파레\r\n");
      out.write("                        </figcaption>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                      <p class=\"short_review \" onclick=\"trackEvent('CLICK_FEATURED_REVIEW')\" data-restaurant_key=\"-jjalqkpiLPa\" data-is_long_reivew=\"\r\n");
      out.write("                        true\r\n");
      out.write("                        \">\r\n");
      out.write("                          맛있다는 평가에는 이유가 있다. 솔직히 햄버거하면 생각나는 건 프랜차이즈와... 맛이라곤 없으면서 산처럼 쌓인 수제버거 뿐이었다. 그래서 지나다...\r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                      <p class=\"long_review \">\r\n");
      out.write("                        맛있다는 평가에는 이유가 있다. 솔직히 햄버거하면 생각나는 건 프랜차이즈와... 맛이라곤 없으면서 산처럼 쌓인 수제버거 뿐이었다. 그래서 지나다니며 늘 인산인해를 이루는 이곳이 신기했다. 우연히 줄이 적어 들어온 날 감동하게 된 것이다. 이렇게 맛있을 줄이야. 기본메뉴세트였는데? 빵도 부드럽고 내용물도 맛있다... 감자튀김도... 맛있었음. 재방문의사 有\r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                        <span class=\"review_more_btn\" onclick=\"trackEvent('CLICK_MORE_REVIEW', {&quot;position&quot;:7,&quot;restaurant_key&quot;:&quot;-jjalqkpiLPa&quot;})\">더보기</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <a href=\"/restaurants/-jjalqkpiLPa\" class=\"btn-detail\"\r\n");
      out.write("                     onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:7,&quot;restaurant_key&quot;:&quot;-jjalqkpiLPa&quot;})\">\r\n");
      out.write("                      <div class=\"restaurant-more-name\">다운타우너</div>\r\n");
      out.write("                      <div class=\"restaurant-more-text\">더보기 ></div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"toplist_list\">\r\n");
      out.write("                <div class=\"with-review\">\r\n");
      out.write("                  <figure class=\"restaurant-item\">\r\n");
      out.write("                    <a href=\"/restaurants/rs2l3jwk3yzh\"\r\n");
      out.write("                      onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:8,&quot;restaurant_key&quot;:&quot;rs2l3jwk3yzh&quot;})\">\r\n");
      out.write("                      <div class=\"thumb\">\r\n");
      out.write("                        <img class=\"center-croping lazy\"\r\n");
      out.write("                             alt=\"팀호완 사진 - 서울특별시 송파구 올림픽로 240 롯데백화점 잠실점 2F\"\r\n");
      out.write("                             data-original=\"https://mp-seoul-image-production-s3.mangoplate.com/1240998_1664322284158996.jpg?fit=around|738:738&amp;crop=738:738;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/kssf5eveeva_xlmy.jpg?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                          />\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption>\r\n");
      out.write("                      <div class=\"info\">\r\n");
      out.write("                        <div class=\"wannago_wrap\">\r\n");
      out.write("                          <button class=\"btn-type-icon favorite wannago_btn \"\r\n");
      out.write("                                  data-restaurant_uuid=\"437434\"\r\n");
      out.write("                                  data-action_id=\"\">\r\n");
      out.write("                          </button>\r\n");
      out.write("                          <p class=\"wannago_txt\">가고싶다 </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"title \">\r\n");
      out.write("                          <a href=\"/restaurants/rs2l3jwk3yzh\"\r\n");
      out.write("                             onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:8,&quot;restaurant_key&quot;:&quot;rs2l3jwk3yzh&quot;})\">\r\n");
      out.write("                            9.<h3> 팀호완</h3>\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <strong class=\"point  \">\r\n");
      out.write("                          <span>4.3</span>\r\n");
      out.write("                        </strong>\r\n");
      out.write("                        <p class=\"etc \">서울특별시 송파구 올림픽로 240 롯데백화점 잠실점 2F</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                  </figure>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"review-content no-bottom\">\r\n");
      out.write("                      <figure class=\"user\">\r\n");
      out.write("                        <div class=\"thumb lazy\"\r\n");
      out.write("                             data-original=\"https://s3-ap-northeast-2.amazonaws.com/mp-seoul-image-production/35328_1673344439686?fit=around|56:56&amp;crop=56:56;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/jmcmlp180qwkp1jj.png?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <figcaption class=\"\">\r\n");
      out.write("                          박길동\r\n");
      out.write("                        </figcaption>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                      <p class=\"short_review \" onclick=\"trackEvent('CLICK_FEATURED_REVIEW')\" data-restaurant_key=\"rs2l3jwk3yzh\" data-is_long_reivew=\"\r\n");
      out.write("                        true\r\n");
      out.write("                        \">\r\n");
      out.write("                          팀호완 잠실점은 롯데월드뷰라 더 좋았어요! 저희는 딤섬 세종류 먹었는데 사천식완탕 이거 최고 맛있어요! 하가우랑 차슈라이스롤 세개다 최고!! 담...\r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                      <p class=\"long_review \">\r\n");
      out.write("                        팀호완 잠실점은 롯데월드뷰라 더 좋았어요! 저희는 딤섬 세종류 먹었는데 사천식완탕 이거 최고 맛있어요! 하가우랑 차슈라이스롤 세개다 최고!! 담에는 제대로 먹으러 갈래요. 여기 완전 맛집이네요:) 저녁에 예약하고 가면 더 예쁠거 같아요~\r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                        <span class=\"review_more_btn\" onclick=\"trackEvent('CLICK_MORE_REVIEW', {&quot;position&quot;:8,&quot;restaurant_key&quot;:&quot;rs2l3jwk3yzh&quot;})\">더보기</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <a href=\"/restaurants/rs2l3jwk3yzh\" class=\"btn-detail\"\r\n");
      out.write("                     onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:8,&quot;restaurant_key&quot;:&quot;rs2l3jwk3yzh&quot;})\">\r\n");
      out.write("                      <div class=\"restaurant-more-name\">팀호완</div>\r\n");
      out.write("                      <div class=\"restaurant-more-text\">더보기 ></div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"toplist_list\">\r\n");
      out.write("                <div class=\"with-review\">\r\n");
      out.write("                  <figure class=\"restaurant-item\">\r\n");
      out.write("                    <a href=\"/restaurants/DrAglGTkfBY0\"\r\n");
      out.write("                      onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:9,&quot;restaurant_key&quot;:&quot;DrAglGTkfBY0&quot;})\">\r\n");
      out.write("                      <div class=\"thumb\">\r\n");
      out.write("                        <img class=\"center-croping lazy\"\r\n");
      out.write("                             alt=\"라이언하트 사진 - 서울특별시 송파구 석촌호수로 284 B 104호\"\r\n");
      out.write("                             data-original=\"https://mp-seoul-image-production-s3.mangoplate.com/363001/1823549_1619320892358_22120?fit=around|738:738&amp;crop=738:738;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/kssf5eveeva_xlmy.jpg?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                          />\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <figcaption>\r\n");
      out.write("                      <div class=\"info\">\r\n");
      out.write("                        <div class=\"wannago_wrap\">\r\n");
      out.write("                          <button class=\"btn-type-icon favorite wannago_btn \"\r\n");
      out.write("                                  data-restaurant_uuid=\"363001\"\r\n");
      out.write("                                  data-action_id=\"\">\r\n");
      out.write("                          </button>\r\n");
      out.write("                          <p class=\"wannago_txt\">가고싶다 </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"title \">\r\n");
      out.write("                          <a href=\"/restaurants/DrAglGTkfBY0\"\r\n");
      out.write("                             onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:9,&quot;restaurant_key&quot;:&quot;DrAglGTkfBY0&quot;})\">\r\n");
      out.write("                            10.<h3> 라이언하트</h3>\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <strong class=\"point  \">\r\n");
      out.write("                          <span>4.3</span>\r\n");
      out.write("                        </strong>\r\n");
      out.write("                        <p class=\"etc \">서울특별시 송파구 석촌호수로 284 B 104호</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </figcaption>\r\n");
      out.write("                  </figure>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"review-content no-bottom\">\r\n");
      out.write("                      <figure class=\"user\">\r\n");
      out.write("                        <div class=\"thumb lazy\"\r\n");
      out.write("                             data-original=\"https://s3-ap-northeast-2.amazonaws.com/mp-seoul-image-production/2252175_1654160857289?fit=around|56:56&amp;crop=56:56;*,*&amp;output-format=jpg&amp;output-quality=80\"\r\n");
      out.write("                             data-error=\"https://mp-seoul-image-production-s3.mangoplate.com/web/resources/jmcmlp180qwkp1jj.png?fit=around|*:*&amp;crop=*:*;*,*&amp;output-format=jpg&amp;output-quality=80\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <figcaption class=\"\">\r\n");
      out.write("                          고균\r\n");
      out.write("                        </figcaption>\r\n");
      out.write("                      </figure>\r\n");
      out.write("                      <p class=\"short_review \" onclick=\"trackEvent('CLICK_FEATURED_REVIEW')\" data-restaurant_key=\"DrAglGTkfBY0\" data-is_long_reivew=\"\r\n");
      out.write("                        true\r\n");
      out.write("                        \">\r\n");
      out.write("                          잠실에 있는 너무 분위기 좋은 스테이크 파스타 집이에요! 친절함은 말할 필요가 없을 정도로 친절하시구 너무 고급스러운 느낌이 나더라구요! 저희는...\r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                      <p class=\"long_review \">\r\n");
      out.write("                        잠실에 있는 너무 분위기 좋은 스테이크 파스타 집이에요! 친절함은 말할 필요가 없을 정도로 친절하시구 너무 고급스러운 느낌이 나더라구요! 저희는 스테이크 200g 새우크림 파스타를 시켰습니다! 하 스테이크에 홀그레인 올려서 먹으면 ..입에서 녹아내려요..진짜 너무 맛있구 새우도 진짜 크고 맛있어요!! 잠실 데이트 코스로 무조건입니당!!\r\n");
      out.write("                      </p>\r\n");
      out.write("\r\n");
      out.write("                        <span class=\"review_more_btn\" onclick=\"trackEvent('CLICK_MORE_REVIEW', {&quot;position&quot;:9,&quot;restaurant_key&quot;:&quot;DrAglGTkfBY0&quot;})\">더보기</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <a href=\"/restaurants/DrAglGTkfBY0\" class=\"btn-detail\"\r\n");
      out.write("                     onclick=\"trackEvent('CLICK_RESTAURANT', {&quot;position&quot;:9,&quot;restaurant_key&quot;:&quot;DrAglGTkfBY0&quot;})\">\r\n");
      out.write("                      <div class=\"restaurant-more-name\">라이언하트</div>\r\n");
      out.write("                      <div class=\"restaurant-more-text\">더보기 ></div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /hyehwaPC/../include/header.jsp(16,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /hyehwaPC/../include/header.jsp(16,2) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/hyehwaPC/../include/header.jsp(16,2) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
